backend:
  name: git-gateway
  branch: main

media_folder: "public/experiment/images"
public_folder: "/experiment/images"

collections:
  - name: "Experiment"
    label: "Experiment"
    folder: "src/experiment"
    create: true
    slug: "experiment"
    fields: 
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
        