backend:
  name: git-gateway
  branch: master

media_folder: "/experiment/images"
public_folder: "/experiment/images"

collections:
  - name: "Experiment"
    label: "Experiment"
    folder: "/experiment"
    create: true
    slug: "experiment"
    delete: false
    fields: 
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
        